# Upptime configuration: https://upptime.js.org/docs/configuration

owner: altspacestudio
repo: tabicamp-status

sites:
  - name: たびキャん 本番（Web）
    url: https://www.tabicamp.jp
    method: HEAD
    expectedStatusCodes:
      - 200
      - 301
      - 302

status-website:
  cname: status.tabicamp.jp
  name: たびキャん Status
  introTitle: "たびキャん の稼働状況"
  introMessage: |
    過去 90 日間の稼働状況をリアルタイムに公開しています。
    障害発生時はこのページで状況を確認できます。
  navbar:
    - title: Status
      href: /
    - title: たびキャん トップ
      href: https://www.tabicamp.jp

assignees:
  - altspacestudio

i18n:
  activeIncidents: 発生中の障害
  allSystemsOperational: 全サービス正常稼働中
  incidentReport: 障害レポート
  pastIncidents: 過去の障害
  resolved: 解決済み

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updates: "0 3 * * *"
  updateTemplate: "0 0 1 * *"
  uptime: "*/5 * * * *"
